#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -eou pipefail

BUILD_DIR="./dist"

function get_img_md5sums {
  find . \
    -type f \
    ! -path "./.git/*" \
    ! -path "${BUILD_DIR}/*" \
    \( -iname "*.avif" -o \
       -iname "*.bmp" -o \
       -iname "*.gif" -o \
       -iname "*.heif" -o \
       -iname "*.jpeg" -o \
       -iname "*.jpg" -o \
       -iname "*.png" -o \
       -iname "*.svg" -o \
       -iname "*.webp" \
    \) \
    -exec md5sum '{}' +
}

function main {
  # Recreate build dir
  rm -rf "${BUILD_DIR}" && mkdir -p "${BUILD_DIR}"

  # Ensure our variables stay local to the function
  local file_basename file_name file_ext file_with_sum

  # Get all image MD5 checksums, write each file to a new
  # file with the checksum in the name.
  while read -r sum file; do
    file_basename=$(basename "${file}")
    file_name="${file_basename%.*}"
    file_ext="${file_basename##*.}"
    file_with_sum="${file_name}.${sum}.${file_ext}"

    cat "${file}" > "${BUILD_DIR}/${file_with_sum}"
  done < <(get_img_md5sums)
}

main
